import { Poppins } from 'next/font/google';
import './globals.css'
import { Inter } from 'next/font/google'
import { Navigation } from "./components/Navigation.jsx";
import { Header } from "./components/Header.jsx";

const inter = Inter({ subsets: ['latin'] })

const poppins = Poppins({
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html className={poppins.className} lang="en">
      <body className={poppins.className}>
          <Header/>
          <Navigation/>
        <section>{children}</section>
        </body>
    </html>
  )
}
